services:
  - type: web
    name: image-scraper-service
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 5001
