    services:
      - type: web
        name: image-scraper-backend
        env: python
        plan: free
        region: oregon
        rootDir: backend
        buildCommand: "pip install -r requirements.txt"
        startCommand: "gunicorn app:app"
        buildpacks:
          - url: https://github.com/heroku/heroku-buildpack-google-chrome
          - url: https://github.com/heroku/heroku-buildpack-chromedriver
        envVars:
          - key: CHROME_BIN
            value: /app/.apt/usr/bin/google-chrome
          - key: CHROMEDRIVER_PATH
            value: /app/.chromedriver/bin/chromedriver
          - key: PYTHON_VERSION
            value: 3.11.4
